### ISSUE TITLE
Projeto eclipse

### ISSUE THREAD

**Issue by FabioTS** [Teodim/Midas#5]
Como posso importar diretamente o nosso projeto para o eclipse?
E o que esse xml tem a ver com isso mael?

**Comment by medisco** [comment]
Para importar o repositório para o eclipse, é necessário ter a versão desktop do GitHub instalado no PC e a extensão EGit instalada no Eclipse. Primeiro você tem clicar na opção "Clone in Desktop" da página web do repositório, essa opção irá abrir o aplicativo do GitHub para Desktop. Depois abra o eclipse e escolha a opção File->Import..., irá abrir um janela e você deverá escolher a opção "Projects from Git" e pressione o botão "Next". Depois escolha a opção "Existing local repository" e pressione o botão "Next". Em seguida escolha o repositório que deseja importar para o eclipse e pressione o o botão "Next" mais 2 vezes e por fim o botão "Finish".

**Comment by FabioTS** [comment]
EGit pode ser encontrado em: http://marketplace.eclipse.org/content/egit-git-team-provider 
Para instalar basta arrastar o botao install para a janela do eclipse.
