### ISSUE TITLE
Codigos nescessários

### ISSUE THREAD

**Issue by FabioTS** [Teodim/Midas#9]
Favor responsáveis pela parte gráfica atualizem o código por mais seco que esteja. Responsáveis pelo banco de dados coloquem algum código que tiverem. Tipo criem um branch e sempre atualizem quando mudarem o código. Isso visa tanto uma maior interação de todos com o projeto quanto com os responsáveis pelas partes em si alem de deixar o projeto atualizado. Não é necessário toda vez que criarem branch façam commits, é só pra deixar up to date mesmo.
Nos responsáveis pelo controller necessitamos saber quais classes e métodos são utilizados em cada parte para organizar o código.
Obrigado.

**Comment by alvarovieira** [comment]
Galera,
sexta temos reuniao com o Uriel pra ele nos direcionar no banco de dados. Até lá peço paciencia a equipe na nossa parte. 

Att. 

Álvaro Torres Vieira
(61) 9611-1075
